name: Integracion Continua (CI)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Compilacion y Pruebas
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Instalar dependencias globales
      run: npm install

    - name: Construir la aplicacion Vanilla JS
      working-directory: ./apps/vanilla
      run: |
        npm install
        npm run build
